import turtle
wn=turtle.Screen()
wn.bgcolor('red')
alex=turtle.Turtle()
alex.color('blue')
alex.pensize(5)
alex.forward(100)
alex.left(90)
alex.forward(100)
alex.left(90)
alex.forward(100)
alex.left(90)
alex.forward(100)
alex.left(90)
